---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    kubeProxyReplacement: true
    k8sServiceHost: <KUBE_API_SERVER_IP>
    k8sServicePort: 6443
    cni:
      chainingMode: "none"
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
    bgpControlPlane:
      enabled: true